### ISSUE TITLE
Hilfslinen im VIS zum Ausrichten von Elementen nicht mehr erkennbar

### ISSUE THREAD

**Issue by thebilberry** [Uhula/ioBroker-Material-Design-Style#10]
Beim Positionieren von Elementen im VIS wurde bislang immer rote Hilfslinen angezeigt, wenn man ein Objekt mit den Cursertasten in die Nähe von anderen Objekten verschoben hat. Seit dem ich Deine Version 2.0 nutze, sind diese Linien aber **weiß** und eigentlich **kaum noch erkennbar**. Vermute, man kann das im CSS umstellen. Hab aber auf die Schnelle keine Stelle gewfunden, wo diese Farbe definiert ist. Bitte um Hilfe.

**Comment by Uhula** [comment]
Ist in der v2.02 bzw. 2.1 korrigiert worden, die Hilfslinien sind wieder da
