### ISSUE TITLE
lnav und rnav lassen sich nicht benutzen

### ISSUE THREAD

**Issue by Knallix** [Uhula/ioBroker-Material-Design-Style#11]
Bin gerade dabei von der V1 auf die V2 zu gehen.
In der Demo gehen leider die rnav und lnav nicht.
Es lassen sich die Buttons nicht drücken. Sobald man z.B. auf Start drück schließt sich die Navigation wieder!
Komme hier nicht weiter. 
Ist hier ein Fehler ?

Gruß
Kevin

**Comment by massimo1971** [comment]
Habe das gleiche Problem, würde die gerne nutzten könne. Bei der MD_Demo geht es gar nicht, bei der MD_Simple geht es aber nur auf dem PC. Am Smartphone kann ich die Lnav und RnaV nicht öffnen

**Comment by Uhula** [comment]
Hast du die Material Design Widgets aus 2018 als Adapter installiert? Die stören, da dort die MDCSS v1.8 enthalten ist.

**Comment by massimo1971** [comment]
Vielen Dank, ja hatte Material Design installiert, nun geht es. Tolle Artbeit :-)

**Comment by Aushilfsarnie** [comment]
Hallo,
ich habe leider dasselbe Problem. Die Widgets habe ich nicht installiert. Woran kann es noch liegen? Auf dem PC geht es, auf dem Handy oder Tablet leider nicht Vielen Dank im Voraus!
