### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by jh2k19** [Uhula/ioBroker-Material-Design-Style#13]
Hallo Uhula, 
ich habe da im css diese Fehler. Woran kann das liegen?

![grafik](https://user-images.githubusercontent.com/51288287/78769265-68927600-798d-11ea-909b-b090a0f027db.png)

Seit ich Material-Design-Style implementiert habe kann ich in den Views keinen Hintergrund wie z.B "H gradient blue 7" mehr verwenden. Der Huntergrund kommt zwar in des VIS aber im Editor zieht die Einstellung nicht mehr. Warum?

Deine Hilfe würde mich freuen.

**Comment by Uhula** [comment]
Die X sind keine Fehler. Dort werden CSS Variablen definiert, welches der Editor noch nicht kennt. Der Browser verarbeitet es sowohl in der vis als auch zur Laufzeit korrekt.
Die view-Hintergründe werden zur Laufzeit durch die gewählte content-Farben überschrieben, sonst würde die Erkennung des light/dark-Themes nicht funktionieren.

**Comment by jh2k19** [comment]
Alles klar und Danke für die schnelle Rückantwort.
