### ISSUE TITLE
images Ordner wohin kopieren?

### ISSUE THREAD

**Issue by Fiiti** [Uhula/ioBroker-Material-Design-Style#3]
Wohin sollten am besten die images aus dem Ordner in vis kopiert werden?

**Comment by Uhula** [comment]
Ich bevorzuge Projekte, bei denen alle beteiligten Dateien dem Projektordner untergeordnet sind. Dann "vergisst" man beim Kopieren nichts und ist nicht auf andere Ordner angewiesen. Wie in dem MD_Demo Projekt, also direkt unterhalb des Projektordners einen Ordner "images" anlegen.

**Comment by Fiiti** [comment]
Danke für Deine Antwort. Jedoch finde ich noch keinen Ansatz im Sinne von iobroker vis in Deiner sonst perfekten Anleitung. Sehr professionell!
Mir ist die Verwendung zur Nutzung einer CSS klar.
**1.)** Ich frage mich jedoch, wo für Dich ein Projekt-Ordner in vis ist? Bei einem normalen html Projekt ist es klar. Aber in vis gibt es im klassischen Sinne dieses nicht (imho).

**2.)** Wo soll ich bitte in vis z. B. die Anweisungen reinschreiben, damit die Klasse auch wirklich angezogen wird?
![2018-01-23 18_47_50-edit vis](https://user-images.githubusercontent.com/25975978/35292179-034cde7c-0070-11e8-8cb6-0fbc1d03c9b7.png)
In diesem Bild habe ich ein Beispiel - aber so kannst Du es ja nicht gemeint haben, oder?

Wenn ich es in den CSS Bereich irgendwo eintrage, verändert vis die Klasse und ich es wird nicht angezogen.

Wie hast Du es also genau bitte gemacht? 

**3.)  Wenn ich Deine Projektdateien in vis erfolgreich importiere, werden jedoch KEINE Grafiken, wie Du sie zeigst, angezeigt. vis zeigt nur bluefox Standardscreen. Ist das richtig?**
Ich nutze vis 1.1.1 - kann es sein, dass es hier export Probleme bei Dir gibt?

**Comment by Uhula** [comment]
zu 1.) Wenn du im vis-Editor den Dateimanager unter Tools öffnest, dann siehst du die Ordnerstruktur. Basierend auf dem root-Ordner / liegen die vis-Projekte im vis.0 Ordner. Bsp: /vis.0/MD_Demo in diesem lege ich mein images-Ordner an.
zu 2.) die CSS Klassen sind unter "Generell / CSS Klasse" anzugeben
zu 3.) ich arbeite noch mit vis 1.0.4, 1.1.1 kenne ich nicht und kann auch nicht sagen, ob dort 1.0.4 Exporte korrekt eingelesen werden können
