### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event

### ISSUE THREAD

**Issue by oke24** [Uhula/ioBroker-Material-Design-Style#6]
Hallo Uhula, ich hoffe Du kannst Dein super MD CSS Framework weiterhin unterstützen. Bei mir hat sich auf dieser Basis ein umfangreiches Projekt entwickelt.

Das Problem ist nur, dass die Ladezeiten auf dem Samsung Tablet A10 immer länger werden - im Moment vom Reload der Seite bis zur Anzeige im Browser 20-30sec. Solange ist die Seite weiss. Im PC-Browser (Chrome wie auch auf dem A10 Tablet) lädt die Seite in ca. 3-5 sec.

Auffällig ist beim Debuggen im Browser das Auftreten vieler jquery-Meldungen in der Browser-Console:

jquery-1.11.2.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
In Deinen MD_Demo Projekt sind das ca. 50 Meldungen und die Seite lädt in ca.3 sec, was gefühlt ok ist.
In meinem größeren Projekt laufen derzeit 300 Meldungen auf, und die Ladezeit geht wie oben beschrieben gegen eine halbe Minute.

Meine Frage ist, ob Du diese Meldungen evtl. kennst, ob diese kritisch für die Performance sind und ggf. einen Tipp hast, wie man sie weg bekommt.

Ich habe zum Vergleich mal andere jquery-Seiten im Debugger mitlaufen lassen, da tauchen die o.g. Meldungen nicht auf und laden auch als jquery-Seiten schnell im Mobile-Chrome.

Ich habe im IOBroker Thread einen Beitrag geschrieben, und ein User hat das Verhalten dort bestätigt.

Ich bin für jeden Tipp dankbar, VG ok

**Comment by Uhula** [comment]
Nun bin ich mal dazu gekommen, mir das anzusehen. Die Meldungen werden nicht durch das MD CSS/Script verursacht, sondern durch die VIS Widgets selbst. Diese registrieren touch-Events ohne die "passive" Angabe. Wobei ich nicht einschätzen kann, ob die nicht auch mit "passive" initiiert werden könnten. Das muss im VIS Core entschieden werden. Wenn du im MD_Demo das (MD)-Skript entfernst kommt die gleiche Anzahl an Meldungen. Nach meiner Einschätzung haben die aber auch keinen Einfluss auf die Ladezeit, sondern wirken sich u.U. nur später aus, wenn du content scrollst.
