### ISSUE TITLE
Dialog leer nach View wechsel

### ISSUE THREAD

**Issue by gaga191281** [Uhula/ioBroker-Material-Design-Style#7]
Bei einem Wechsel einer View in eine andere über die "top app bar" und wieder zurück ist beim Öffnen eines Dialoges dieser leer. Lediglich Überschrift und Schließen-Button sind noch zu sehen. Alle Komponenten wie Buttons, etc. sind weg. Es hilft nur ein Neuladen der Seite.

**Comment by Pittini** [comment]
> Bei einem Wechsel einer View in eine andere über die "top app bar" und wieder zurück ist beim Öffnen eines Dialoges dieser leer. Lediglich Überschrift und Schließen-Button sind noch zu sehen. Alle Komponenten wie Buttons, etc. sind weg. Es hilft nur ein Neuladen der Seite.

Da ich nix von einer "top app bar" beim MaterialDesign von Uhula weis, die Frage an Dich: Was genau meinst Du? Betrifft das Problem tatsächlich das script von Uhula oder gehts um den Material Design Adapter? Weil wenn letzteres, biste hier falsch.

**Comment by gaga191281** [comment]
Sorry, du hast natürlich recht. Es handelt sich um den Adapter... bin schon weg :P
