### ISSUE TITLE
Update eines bestehenden Projekts auf 2.0

### ISSUE THREAD

**Issue by thebilberry** [Uhula/ioBroker-Material-Design-Style#8]
Ich war von der Vorgängerversion ja schon total begeistert. Die Version 2.0 bietet nun noch genau die Features, die ich bislang noch vermisst habe. Vielen Dank dafür!

Meine Frage ist aber, ob ich mein bestehendes Projekt ohne weiteres auf die neue Version updaten kann oder ob gravierende Anpassungen nötig sind? Vielleicht kannst Du hier auf github eine kurze Beschreibung der nötigen/empfohlenen Schritte für ein Update hinterlegen?

**Comment by Uhula** [comment]
Eine Kurzübersicht ist in der readme.MD nun vorhanden.
